### ISSUE TITLE
Uplift env5-base-project to current enV5 version

### ISSUE THREAD

**Issue by DavidFederl** [es-ude/enV5-base-project#6]
Update the current enV5-base branch to the latest changes.

## ToDo's

- [ ] change included enV5 version from release tag to `main` (see helpers.cmake)
- [ ] Update _README_ to state that if fixed enV5 version is required `helpers.cmake` needs to be modified after forking repo
- [ ] Update settings for pico-sdk (see pico-sdk)

### helpers.cmake

```cmake
...
FetchContent_Declare(
    runtime_env5
     GIT_REPOSITORY https://github.com/es-ude/elastic-ai.runtime.enV5.git
    GIT_TAG main
)
....
```

### pico-sdk

```cmake
...
set(PICO_SDK_FETCH_FROM_GIT on)
set(PICO_BOARD none)
set(PICO_PLATFORM rp2040)
set(PICOTOOL_FETCH_FROM_GIT_PATH ${CMAKE_SOURCE_DIR}/picotool)
include(pico_sdk_import.cmake)
...
```

**Comment by DavidFederl** [comment]
will be completed with #9
